---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "slurmtalks-backend.fullname" . }}
data:
  POSTGRES_USER: {{ .Values.configmap.POSTGRES_USER }}
  POSTGRES_DB: {{ .Values.configmap.POSTGRES_DB }}
  POSTGRES_HOST: {{ .Values.configmap.POSTGRES_HOST }}
  POSTGRES_PORT: {{ .Values.configmap.POSTGRES_PORT | quote }}
  REDIS_ADDR: {{ .Values.configmap.REDIS_ADDR }}
  REDIS_DB: {{ .Values.configmap.REDIS_DB | quote }}
  MIGRATE_IN_CODE: {{ .Values.configmap.MIGRATE_IN_CODE | quote }}
  NEXT_PUBLIC_BACKEND_URL: {{ .Values.configmap.NEXT_PUBLIC_BACKEND_URL }}