---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "slurmtalks-backend.fullname" . }}
stringData:
  POSTGRES_PASSWORD: {{ .Values.secret.POSTGRES_PASSWORD }}
  REDIS_PASSWORD: {{ .Values.secret.REDIS_PASSWORD }}
  JWT_SECRET_KEY: {{ .Values.secret.JWT_SECRET_KEY }}
